name: portfolio
version: 1.0.0+1
publish_to: none
description: Portfolio developed in flutter.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  animated_glitch: ^2.0.0+2
  auto_size_text: ^3.0.0
  build_runner: ^2.4.5
  collection: ^1.17.1
  envied: ^0.5.4+1
  firebase_core: ^3.6.0
  flex_color_scheme: ^7.1.2
  flutter: 
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.14.1
  flutter_localizations: 
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  riverpod_annotation: ^2.1.1
  seo: ^0.0.4
  url_launcher: ^6.1.11
  url_strategy: ^0.3.0

dev_dependencies: 
  custom_lint: ^0.6.4
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter
  patrol: ^3.11.2
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.6.1

flutter: 
  assets: 
    - assets/images/
    - assets/projects/
  uses-material-design: true
  generate: true

fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/nunito/static/Nunito-Regular.ttf


patrol:
  app_name: portfolio
  android:
    package_name: com.example.portfolio
  ios:
    bundle_id: com.example.portfolio
